# Generated by Django 5.2 on 2025-04-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
